version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rehearsal_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rehearsal_scheduler
      SENDGRID_KEY: your_sendgrid_key
      TWILIO_KEY: your_twilio_key
      GOOGLE_CLIENT_ID: your_google_client_id
      STRIPE_KEY: your_stripe_key
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  pgdata:
